export const SET_ACTIVE_USER = "SET_ACTIVE_USER_ID";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SET_ACTIVE_USER_TOKEN = "SET_ACTIVE_USER_TOKEN";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";
export const SET_PAGE_VISIBILITY = "SET_PAGE_VISIBILITY";
