export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SET_ACTIVE_USER_TOKEN = "SET_ACTIVE_USER_TOKEN";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";